### ISSUE TITLE
Do not lock screen when running from Live ISO

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/deepin-desktop-schemas#2]
Do not lock screen when running from Live ISO. 

On Live ISO, the default user account has no password. But then the screen is locked, the empty password is not accepted and the user cannot login. 

https://github.com/linuxdeepin/deepin-desktop-schemas/blob/8aed17fe275bc43d700befa0a7d1bac9844d7c08/schemas/com.deepin.dde.power.gschema.xml#L33-L37

Workaround:
Kill X session.

**Comment by probonopd** [comment]
Possilbly this could be fixed with 

```
dconf write /org/gnome/desktop/screensaver/lock-enabled false
dconf write /com/deepin/wrap/gnome/desktop/screensaver/lock-enabled false
```

This should be changed by default on the Live ISO.

**Comment by probonopd** [comment]
cc @jingle0927

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by justforlxz** [comment]
I created a new issue to track.
https://github.com/linuxdeepin/developer-center/issues/2081
