### ISSUE TITLE
.service file not found

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/deepin-desktop-schemas#20]
Hello, I'm trying to do a dark mode for deepin and a silent mode, but I have a problem: I'm a starter an d when I use QDBusMessage to edit a value of com.deepin.daemon.Audio, I have:
QDBusMessage(type=Error, service="org.freedesktop.DBus", error name="org.freedesktop.DBus.Error.ServiceUnknown", error message="The name com.deepin.daemon.Audio was not provided by any .service files", signature="s", contents=("The name com.deepin.daemon.Audio was not provided by any .service files") )
But I've checked in on my disk, and I have (in reality, but to check in case of...), so, I ask you to help me, I use:
    QDBusInterface interface( "com.deepin.daemon.Audio",
                                  "/Audio/Sink0",
                                  "org.freedesktop.DBus.Properties",
                                  QDBusConnection::systemBus() );
    QDBusMessage result = interface.call( "setVolume",
                                              "com.deepin.daemon.Audio.Sink", "0,1");
    qDebug() << result;

I tryed to use the sound components of dde-dock an dde-top-bar to find a way, but when I use it, my app crash.
e.g.: I use qmake and my project is available at https:://www.github.com/N1coc4colA/Modes

**Comment by N1coc4colA** [comment]
Now I'm experimenting a new issue, or more exactly some issues:
process 28535: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1371.
This is normally a bug in some application using the D-Bus library.
process 28535: arguments to dbus_message_set_auto_start() were incorrect, assertion "message != NULL" failed in file ../../../dbus/dbus-message.c line 3120.
This is normally a bug in some application using the D-Bus library.
process 28535: arguments to dbus_message_iter_init_append() were incorrect, assertion "message != NULL" failed in file ../../../dbus/dbus-message.c line 2504.
This is normally a bug in some application using the D-Bus library.
QDBusConnection: error: could not send message to service "com.deepin.daemon.Audio" path "com/deepin/daemon/Audio" interface "org.freedesktop.DBus.Introspectable" member "Introspect":

**Comment by BLumia** [comment]
@electricface

**Comment by N1coc4colA** [comment]
Hello, sorry, now, I can handle the dbus with this package, thanks for the support (not ironic, cause when I want to send a message to get help, the light is XD). Now I can edit values using DBus, you can check my app to see ;)
