### ISSUE TITLE
Unreleased last changes cause login issues

### ISSUE THREAD

**Issue by Swizz** [linuxdeepin/deepin-desktop-schemas#3]
[`startdde 3.1.27-1`](https://www.archlinux.org/packages/community/x86_64/startdde/) was released on ArchLinux but depends on [some changes](https://github.com/linuxdeepin/deepin-desktop-schemas/commit/3591218f7eb1ed9b1f62af43ace5e707e0260575#diff-5af4ed71a05f9eef24a8694e2ec421b4) in `deepin-desktop-schemas`.

This lead to an unexpected issue that make ArchLinux deepin user unable to log in. 

See : 
- linuxdeepin/startdde#9
- https://bugs.archlinux.org/task/58179

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
