### ISSUE TITLE
The last update leaves the desktop unusable

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/deepin-desktop-schemas#4]
Hi, i updated this package today and i got a horrible bug: 
Desktop does not load the background wallpaper, also does not load the toolbar(dock), or any other decorative in desktop, `deepin` does not load any program, whatever i want, and i can open right menu: i can open from here the settings and the terminal, but terminal does not works too.

I had to downgrade to the last version and all is well now, thank you.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
